### ISSUE TITLE
Use category "Programming Languages" instead of "Language Packs"

### ISSUE THREAD

**Issue by gregvanl** [luozhihua/vscode-parallel-components-editor#1]
The Language Packs category is for display language (German, Japanese) extensions. I think you want to use the category "Programming Languages". You would update your package.json "categories" entry.

**Comment by luozhihua** [comment]
Thanks for your valuable Suggestions, the next version will be revised.

**Comment by gregvanl** [comment]
Any progress on this? I still see this extension listed.

![image](https://user-images.githubusercontent.com/12818376/42003907-662b72a2-7a22-11e8-8455-634d5a0524e4.png)

**Comment by gregvanl** [comment]
Hi @luozhihua, have you been able to republish your extension? Yours is the last non-Language Pack in the query.  Thanks

![image](https://user-images.githubusercontent.com/12818376/42292873-9ba1b104-7f8a-11e8-8f4c-fae8cdbe6863.png)

**Comment by JacksonKearl** [comment]
Hey @luozhihua just following up on if you have published the changes yet. Still seeing it as a language pack on our end. Thanks!

**Comment by luozhihua** [comment]
Sorry, I published a new version with a new name: `Parallel Space`, I don't know how to remove the old version from marketplace now, any one can help me to do that?

**Comment by ramya-rao-a** [comment]
Try running `vsce unpublish` followed by the extension id

**Comment by luozhihua** [comment]
@ramya-rao-a : Thanks.

@gregvanl @JacksonKearl : I removed the extensions from Marketplace, I'm sorry for the inconvenience.

**Comment by gregvanl** [comment]
@luozhihua Awesome, Thanks!
